[project]
name = "ai-agent-human-in-loop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.5",
    "typing>=3.10.0.0",
]
